name: C++ CI/CD

on:
  push:
    branches: [ master ]
    tags:
      - 'v1.0.*'
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine version (1.0.N)
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v1.0.* ]]; then
          N=${GITHUB_REF#refs/tags/v1.0.}
        else
          N=${{ github.run_number }}
        fi
        echo "VERSION=1.0.$N" >> $GITHUB_ENV
        echo "Building version: 1.0.$N"

    - name: Configure CMake
      run: cmake -S . -B build -DPROJECT_VERSION=${{ env.VERSION }}

    - name: Build
      run: cmake --build build --config Release

    - name: Run program
      run: ./build/Lab1